default:
  theme_advanced_toolbar_align: left
  theme_advanced_buttons3_add:
    - tablecontrols
  plugins:
    - table

caboose:
  width: '540px'
  height: '130px'
  convert_urls: false
  content_css: '/assets/caboose/tinymce.css'
  theme_advanced_toolbar_location: top
  theme_advanced_toolbar_align: left
  theme_advanced_statusbar_location: bottom
  theme_advanced_resizing: true
  theme_advanced_buttons1: "bold,italic,underline,|,bullist,numlist,|,link,unlink,anchor,image,|,tablecontrols,|,code"
  theme_advanced_buttons2: ""
  theme_advanced_buttons3: ""
  theme_advanced_buttons4: ""            
  plugins: "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template"
